# Generated by Django 5.0.7 on 2024-10-14 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('attractionid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('attractionname', models.CharField(max_length=100)),
                ('attdescription', models.TextField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('opening_hours', models.CharField(max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('custid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('custname', models.CharField(max_length=50)),
                ('custphone', models.CharField(max_length=12)),
                ('custmail', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('packageid', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('packagename', models.CharField(max_length=100)),
                ('destinations', models.TextField()),
                ('tourdescription', models.TextField()),
                ('price', models.FloatField()),
                ('durationdays', models.IntegerField()),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookingdate', models.DateField()),
                ('totalprice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('attractionid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terengganu.attraction')),
                ('custid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terengganu.customer')),
            ],
        ),
        migrations.AddField(
            model_name='attraction',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terengganu.package'),
        ),
    ]
