# Generated by Django 5.0.7 on 2024-10-16 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terengganu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attraction',
            name='attractionid',
            field=models.AutoField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='custid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='package',
            name='packageid',
            field=models.AutoField(max_length=4, primary_key=True, serialize=False),
        ),
    ]
