# Generated by Django 5.0.7 on 2024-10-16 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terengganu', '0002_alter_attraction_attractionid_alter_customer_custid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attraction',
            name='attractionid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='package',
            name='packageid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
