# Generated by Django 5.0.7 on 2024-10-16 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terengganu', '0003_alter_attraction_attractionid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='custmail',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
