# Generated by Django 5.0.7 on 2024-10-19 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terengganu', '0005_alter_customer_custmail'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='username',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
