# Generated by Django 5.0.7 on 2024-10-16 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terengganu', '0004_alter_customer_custmail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='custmail',
            field=models.EmailField(max_length=254),
        ),
    ]
