# Generated by Django 5.0.7 on 2024-10-19 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terengganu', '0006_customer_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attraction',
            old_name='price',
            new_name='attprice',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='price',
            new_name='packageprice',
        ),
    ]
