# Generated by Django 5.0.7 on 2024-10-19 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terengganu', '0007_rename_price_attraction_attprice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='attractionid',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='custid',
        ),
        migrations.DeleteModel(
            name='Attraction',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
