# Generated by Django 5.0.7 on 2024-10-19 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terengganu', '0008_remove_booking_attractionid_remove_booking_custid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('bookingid', models.AutoField(primary_key=True, serialize=False)),
                ('bookingdate', models.DateField()),
                ('bookingticket', models.IntegerField()),
                ('totalprice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('custid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terengganu.customer')),
                ('packageid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terengganu.package')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewcomment', models.TextField()),
                ('custid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terengganu.customer')),
            ],
        ),
    ]
